/* tslint:disable */
/* eslint-disable */
/**
 * REST API SPEC FOR MOVESONG FRONTEND
 * REST API SPEC FOR MOVESONG FRONTEND
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConnectionDto } from './connection-dto';
/**
 * 
 * @export
 * @interface FindConnectionsByMovesongEmailResp
 */
export interface FindConnectionsByMovesongEmailResp {
    /**
     * 
     * @type {Array<ConnectionDto>}
     * @memberof FindConnectionsByMovesongEmailResp
     */
    connections?: Array<ConnectionDto>;
}
