/* tslint:disable */
/* eslint-disable */
/**
 * REST API SPEC FOR MOVESONG FRONTEND
 * REST API SPEC FOR MOVESONG FRONTEND
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FindSubscriptionResp
 */
export interface FindSubscriptionResp {
    /**
     * 
     * @type {number}
     * @memberof FindSubscriptionResp
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    productId?: string;
    /**
     * 
     * @type {number}
     * @memberof FindSubscriptionResp
     */
    currentPeriodEnd?: number;
    /**
     * 
     * @type {number}
     * @memberof FindSubscriptionResp
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof FindSubscriptionResp
     */
    interval?: string;
}
