/* tslint:disable */
/* eslint-disable */
/**
 * REST API SPEC FOR MOVESONG FRONTEND
 * REST API SPEC FOR MOVESONG FRONTEND
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LoginResp
 */
export interface LoginResp {

    /**
     * @type {number}
     * @memberof LoginResp
     */
    id?: number;

    /**
     * @type {string}
     * @memberof LoginResp
     */
    accessToken?: string;

    /**
     * @type {string}
     * @memberof LoginResp
     */
    email?: string;

    /**
     * @type {string}
     * @memberof LoginResp
     */
    username?: string;

    /**
     * @type {string}
     * @memberof LoginResp
     */
    firstName?: string;

    /**
     * @type {string}
     * @memberof LoginResp
     */
    lastName?: string;
}
