/* tslint:disable */
/* eslint-disable */
/**
 * REST API SPEC FOR MOVESONG FRONTEND
 * REST API SPEC FOR MOVESONG FRONTEND
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SendEmailReq
 */
export interface SendEmailReq {
    /**
     * 
     * @type {string}
     * @memberof SendEmailReq
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailReq
     */
    emailType?: SendEmailReqEmailTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SendEmailReq
     */
    token?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SendEmailReqEmailTypeEnum {
    RESETPASSWORD = 'RESET_PASSWORD',
    CONFIRMREGISTRATION = 'CONFIRM_REGISTRATION',
    CONTACT = 'CONTACT'
}

