/* tslint:disable */
/* eslint-disable */
/**
 * REST API SPEC FOR MOVESONG FRONTEND
 * REST API SPEC FOR MOVESONG FRONTEND
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CancelSubscriptionReq } from '../models';
import { CancelSubscriptionResp } from '../models';
import { FindSubscriptionByUserEmailReq } from '../models';
import { FindSubscriptionReq } from '../models';
import { FindSubscriptionResp } from '../models';
import { SaveSubscriptionReq } from '../models';
import { SaveSubscriptionResp } from '../models';
import { SubscriptionReq } from '../models';
import { SubscriptionResp } from '../models';
/**
 * SubscriptionApi - axios parameter creator
 * @export
 */
export const SubscriptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary cancelSubscription 
         * @param {CancelSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelSubscription: async (body?: CancelSubscriptionReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cancelSubscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = '*/*';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary findSubscription 
         * @param {FindSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSubscription: async (body?: FindSubscriptionReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/findSubscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = '*/*';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary findSubscriptionByUserEmail 
         * @param {FindSubscriptionByUserEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSubscriptionByUserEmail: async (body?: FindSubscriptionByUserEmailReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/findSubscriptionByUserEmail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = '*/*';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary saveSubscription 
         * @param {SaveSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSubscription: async (body?: SaveSubscriptionReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/saveSubscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = '*/*';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary subscription 
         * @param {SubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscription: async (body?: SubscriptionReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = '*/*';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionApi - functional programming interface
 * @export
 */
export const SubscriptionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary cancelSubscription 
         * @param {CancelSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelSubscription(body?: CancelSubscriptionReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CancelSubscriptionResp>>> {
            const localVarAxiosArgs = await SubscriptionApiAxiosParamCreator(configuration).cancelSubscription(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary findSubscription 
         * @param {FindSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSubscription(body?: FindSubscriptionReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<FindSubscriptionResp>>> {
            const localVarAxiosArgs = await SubscriptionApiAxiosParamCreator(configuration).findSubscription(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary findSubscriptionByUserEmail 
         * @param {FindSubscriptionByUserEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSubscriptionByUserEmail(body?: FindSubscriptionByUserEmailReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<FindSubscriptionResp>>> {
            const localVarAxiosArgs = await SubscriptionApiAxiosParamCreator(configuration).findSubscriptionByUserEmail(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary saveSubscription 
         * @param {SaveSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSubscription(body?: SaveSubscriptionReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SaveSubscriptionResp>>> {
            const localVarAxiosArgs = await SubscriptionApiAxiosParamCreator(configuration).saveSubscription(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary subscription 
         * @param {SubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscription(body?: SubscriptionReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SubscriptionResp>>> {
            const localVarAxiosArgs = await SubscriptionApiAxiosParamCreator(configuration).subscription(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SubscriptionApi - factory interface
 * @export
 */
export const SubscriptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary cancelSubscription 
         * @param {CancelSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelSubscription(body?: CancelSubscriptionReq, options?: AxiosRequestConfig): Promise<AxiosResponse<CancelSubscriptionResp>> {
            return SubscriptionApiFp(configuration).cancelSubscription(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary findSubscription 
         * @param {FindSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSubscription(body?: FindSubscriptionReq, options?: AxiosRequestConfig): Promise<AxiosResponse<FindSubscriptionResp>> {
            return SubscriptionApiFp(configuration).findSubscription(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary findSubscriptionByUserEmail 
         * @param {FindSubscriptionByUserEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSubscriptionByUserEmail(body?: FindSubscriptionByUserEmailReq, options?: AxiosRequestConfig): Promise<AxiosResponse<FindSubscriptionResp>> {
            return SubscriptionApiFp(configuration).findSubscriptionByUserEmail(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary saveSubscription 
         * @param {SaveSubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSubscription(body?: SaveSubscriptionReq, options?: AxiosRequestConfig): Promise<AxiosResponse<SaveSubscriptionResp>> {
            return SubscriptionApiFp(configuration).saveSubscription(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary subscription 
         * @param {SubscriptionReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscription(body?: SubscriptionReq, options?: AxiosRequestConfig): Promise<AxiosResponse<SubscriptionResp>> {
            return SubscriptionApiFp(configuration).subscription(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubscriptionApi - object-oriented interface
 * @export
 * @class SubscriptionApi
 * @extends {BaseAPI}
 */
export class SubscriptionApi extends BaseAPI {
    /**
     * 
     * @summary cancelSubscription 
     * @param {CancelSubscriptionReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public async cancelSubscription(body?: CancelSubscriptionReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<CancelSubscriptionResp>> {
        return SubscriptionApiFp(this.configuration).cancelSubscription(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary findSubscription 
     * @param {FindSubscriptionReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public async findSubscription(body?: FindSubscriptionReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<FindSubscriptionResp>> {
        return SubscriptionApiFp(this.configuration).findSubscription(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary findSubscriptionByUserEmail 
     * @param {FindSubscriptionByUserEmailReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public async findSubscriptionByUserEmail(body?: FindSubscriptionByUserEmailReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<FindSubscriptionResp>> {
        return SubscriptionApiFp(this.configuration).findSubscriptionByUserEmail(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary saveSubscription 
     * @param {SaveSubscriptionReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public async saveSubscription(body?: SaveSubscriptionReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<SaveSubscriptionResp>> {
        return SubscriptionApiFp(this.configuration).saveSubscription(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary subscription 
     * @param {SubscriptionReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public async subscription(body?: SubscriptionReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<SubscriptionResp>> {
        return SubscriptionApiFp(this.configuration).subscription(body, options).then((request) => request(this.axios, this.basePath));
    }
}
